# Generated by Django 4.2.6 on 2023-10-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
    ]
